// Interface automatically generated by schemas-to-ts

export interface Gas {
  prezzo?: string;
  quota_fissa?: string;
}
export interface Gas_Plain {
  prezzo?: string;
  quota_fissa?: string;
}

export interface Gas_NoRelations {
  prezzo?: string;
  quota_fissa?: string;
}

