// Interface automatically generated by schemas-to-ts

export interface Luce {
  prezzo?: string;
  quota_fissa?: string;
}
export interface Luce_Plain {
  prezzo?: string;
  quota_fissa?: string;
}

export interface Luce_NoRelations {
  prezzo?: string;
  quota_fissa?: string;
}

