// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Luce } from '../../../../components/componenti-offerta/interfaces/Luce';
import { Gas } from '../../../../components/componenti-offerta/interfaces/Gas';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { MetaSocial } from '../../../../components/shared/interfaces/MetaSocial';
import { Luce_Plain } from '../../../../components/componenti-offerta/interfaces/Luce';
import { Gas_Plain } from '../../../../components/componenti-offerta/interfaces/Gas';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { MetaSocial_Plain } from '../../../../components/shared/interfaces/MetaSocial';
import { Luce_NoRelations } from '../../../../components/componenti-offerta/interfaces/Luce';
import { Gas_NoRelations } from '../../../../components/componenti-offerta/interfaces/Gas';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { MetaSocial_NoRelations } from '../../../../components/shared/interfaces/MetaSocial';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Indicizzato {
  NonArera = 'Non ARERA',
  Arera = 'ARERA',}

export interface Offerta {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Nome: string;
    asset_media?: { data: Media };
    Esclusiva?: boolean;
    Descrizione?: string;
    Dettaglio?: string;
    Luce?: Luce;
    Gas?: Gas;
    seo: Seo[];
    metaSocial: MetaSocial[];
    Indicizzato: Indicizzato;
    Slug?: string;
    Pagamento: any;
    Asseturl?: string;
    Asset_url?: string;
  };
}
export interface Offerta_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Nome: string;
  asset_media?: Media;
  Esclusiva?: boolean;
  Descrizione?: string;
  Dettaglio?: string;
  Luce?: Luce_Plain;
  Gas?: Gas_Plain;
  seo: Seo_Plain[];
  metaSocial: MetaSocial_Plain[];
  Indicizzato: Indicizzato;
  Slug?: string;
  Pagamento: any;
  Asseturl?: string;
  Asset_url?: string;
}

export interface Offerta_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Nome: string;
  asset_media?: number;
  Esclusiva?: boolean;
  Descrizione?: string;
  Dettaglio?: string;
  Luce?: Luce_NoRelations;
  Gas?: Gas_NoRelations;
  seo: Seo_NoRelations[];
  metaSocial: MetaSocial_NoRelations[];
  Indicizzato: Indicizzato;
  Slug?: string;
  Pagamento: any;
  Asseturl?: string;
  Asset_url?: string;
}

export interface Offerta_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Nome: string;
  asset_media?: AdminPanelRelationPropertyModification<Media>;
  Esclusiva?: boolean;
  Descrizione?: string;
  Dettaglio?: string;
  Luce?: Luce_Plain;
  Gas?: Gas_Plain;
  seo: Seo_Plain[];
  metaSocial: MetaSocial_Plain[];
  Indicizzato: Indicizzato;
  Slug?: string;
  Pagamento: any;
  Asseturl?: string;
  Asset_url?: string;
}
