// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Luce } from '../../../../components/componenti-offerta/interfaces/Luce';
import { Gas } from '../../../../components/componenti-offerta/interfaces/Gas';
import { Luce_Plain } from '../../../../components/componenti-offerta/interfaces/Luce';
import { Gas_Plain } from '../../../../components/componenti-offerta/interfaces/Gas';
import { Luce_NoRelations } from '../../../../components/componenti-offerta/interfaces/Luce';
import { Gas_NoRelations } from '../../../../components/componenti-offerta/interfaces/Gas';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Offerta {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    nome: string;
    Asset: { data: Media };
    Esclusiva?: boolean;
    Descrizione?: string;
    Dettaglio?: string;
    Indicizzato?: string;
    Pagamento?: string;
    luce?: Luce;
    Gas?: Gas;
  };
}
export interface Offerta_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  nome: string;
  Asset: Media;
  Esclusiva?: boolean;
  Descrizione?: string;
  Dettaglio?: string;
  Indicizzato?: string;
  Pagamento?: string;
  luce?: Luce_Plain;
  Gas?: Gas_Plain;
}

export interface Offerta_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  nome: string;
  Asset: number;
  Esclusiva?: boolean;
  Descrizione?: string;
  Dettaglio?: string;
  Indicizzato?: string;
  Pagamento?: string;
  luce?: Luce_NoRelations;
  Gas?: Gas_NoRelations;
}

export interface Offerta_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  nome: string;
  Asset: AdminPanelRelationPropertyModification<Media>;
  Esclusiva?: boolean;
  Descrizione?: string;
  Dettaglio?: string;
  Indicizzato?: string;
  Pagamento?: string;
  luce?: Luce_Plain;
  Gas?: Gas_Plain;
}
